name: dbox
description: "Dart wrapped network library via Golang FFI"
version: 0.0.2

platforms:
  android:
  ios:
  linux:
  macos:
  # web:
  windows:

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  ffi: ^2.1.4

dev_dependencies:
  ffigen: ^17.0.0
  lints: ^5.0.0
  test: ^1.24.0