name: dox
description: "Dart wrapped network library via Golang FFI"
version: 0.0.1
environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: 3.29.1

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4
  ffigen: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0