name: dox
description: "Dart wrapped network library via Golang FFI"
version: 0.0.1
environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  ffi: ^2.1.4
  ffigen: ^17.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0