name: DBox
description: "Dart wrapped network library via Golang FFI"
version: 0.0.3

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  ffi: ^2.1.4

dev_dependencies:
  ffigen: ^18.0.0
  lints: ^5.0.0
  test: ^1.24.0