name: android

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SOURCE_DIR: external

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build-android.yml"
  workflow_dispatch:
  workflow_run:
    workflows: ["listen", "ci"]
    types:
      - completed

jobs:
  parse-info:
    uses: ./.github/workflows/parse-info.yml
    with:
      path: 'pubspec.yaml'
      target: 'android'

  build-android:
    needs: parse-info
    runs-on: ubuntu-latest
    env:
      PKG: ${{ needs.parse-info.outputs.name_lower }}
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: |
          LATEST_NDK=$(sdkmanager --list | grep -o "ndk;[0-9.]*" | sort -V | tail -1)
          echo "Installing $LATEST_NDK"
          yes | sdkmanager --install "$LATEST_NDK"
          
          NDK_VERSION=$(echo $LATEST_NDK | cut -d';' -f2)
          echo "Using NDK version: $NDK_VERSION"
          
          echo "ANDROID_SDK=$ANDROID_HOME" >> $GITHUB_ENV
          echo "NDK_BIN=$ANDROID_HOME/ndk/$NDK_VERSION/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_ENV

      - name: Set up environment variables
        run: |
          echo "BUILD_DIR=$GITHUB_WORKSPACE/platforms/android" >> $GITHUB_ENV

          if [ -d "$SOURCE_DIR" ]; then
            echo "WORKING_DIR=$GITHUB_WORKSPACE/$SOURCE_DIR" >> $GITHUB_ENV
          else
            echo "WORKING_DIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          fi

      - name: Clean and Create output directories
        run: |
          rm -rf $BUILD_DIR
          mkdir -p $BUILD_DIR/src/main/jniLibs/arm64-v8a
          mkdir -p $BUILD_DIR/src/main/jniLibs/armeabi-v7a
          mkdir -p $BUILD_DIR/src/main/jniLibs/x86_64
          mkdir -p $BUILD_DIR/src/main/jniLibs/x86

      - name: Build for arm64-v8a
        run: |
          echo "Building for arm64-v8a..."
          cd $WORKING_DIR
          ARCH="arm64" CGO_ENABLED=1 GOOS=android GOARCH=$ARCH \
            CC=$NDK_BIN/aarch64-linux-android21-clang \
            go build -buildmode=c-shared \
            -trimpath \
            -ldflags="-s -w -buildid=" \
            -tags="with_debug" \
            -o "$BUILD_DIR/src/main/jniLibs/arm64-v8a/lib${PKG}.so" \
            ./cmd/${PKG}

      - name: Build for armeabi-v7a
        run: |
          echo "Building for armeabi-v7a..."
          cd $WORKING_DIR
          ARCH="arm" CGO_ENABLED=1 GOOS=android GOARCH=$ARCH GOARM=7 \
            CC=$NDK_BIN/armv7a-linux-androideabi21-clang \
            go build -buildmode=c-shared \
            -trimpath \
            -ldflags="-s -w -buildid=" \
            -tags="with_debug" \
            -o "$BUILD_DIR/src/main/jniLibs/armeabi-v7a/lib${PKG}.so" \
            ./cmd/${PKG}

      - name: Build for x86_64
        run: |
          echo "Building for x86_64..."
          cd $WORKING_DIR
          ARCH="amd64" CGO_ENABLED=1 GOOS=android GOARCH=amd64 \
            CC=$NDK_BIN/x86_64-linux-android21-clang \
            go build -buildmode=c-shared \
            -trimpath \
            -ldflags="-s -w -buildid=" \
            -tags="with_debug" \
            -o "$BUILD_DIR/src/main/jniLibs/x86_64/lib${PKG}.so" \
            ./cmd/${PKG}

      - name: Build for x86
        run: |
          echo "Building for x86..."
          cd $WORKING_DIR
          ARCH="386" CGO_ENABLED=1 GOOS=android GOARCH=$ARCH \
            CC=$NDK_BIN/i686-linux-android21-clang \
            go build -buildmode=c-shared \
            -trimpath \
            -ldflags="-s -w -buildid=" \
            -tags="with_debug" \
            -o "$BUILD_DIR/src/main/jniLibs/x86/lib${PKG}.so" \
            ./cmd/${PKG}

      - name: Commit and push changes
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          git stash -u
          git pull --rebase
          git stash pop || true
          git add $BUILD_DIR/src/main/jniLibs
          
          if git diff --staged --quiet; then
            echo "No changes detected in Android libraries. Skipping commit."
          else
            echo "Changes detected in Android libraries. Creating commit..."
            git commit -m "Build Android libraries ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            git push
            echo "Successfully pushed changes to repository."
          fi