name: linux

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BUILD_DIR: native/linux
  SOURCE_DIR: external

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build-linux.yml"
  workflow_dispatch:
  workflow_run:
    workflows: ["listen", "ci"]
    types:
      - completed

jobs:
  parse-info:
    uses: ./.github/workflows/parse-info.yml
    with:
      path: 'pubspec.yaml'
      target: 'linux'

  build-linux:
    runs-on: ubuntu-latest
    needs: parse-info
    env:
      PKG: ${{ needs.parse-info.outputs.name_lower }}
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Install cross-compilation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf gcc-i686-linux-gnu

      - name: Set up environment variables
        run: |
          echo "BUILD_DIR=$GITHUB_WORKSPACE/$BUILD_DIR" >> $GITHUB_ENV
          if [ -d "$SOURCE_DIR" ]; then
            echo "WORKING_DIR=$GITHUB_WORKSPACE/$SOURCE_DIR" >> $GITHUB_ENV
          else
            echo "WORKING_DIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          fi

      - name: Clean and Create output directories
        run: |
          rm -rf $BUILD_DIR
          mkdir -p $BUILD_DIR/lib/amd64
          mkdir -p $BUILD_DIR/lib/arm64
          mkdir -p $BUILD_DIR/lib/386
          mkdir -p $BUILD_DIR/lib/armv7

      - name: Build for Linux AMD64
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          echo "Building for Linux AMD64..."
          GOOS=linux GOARCH=amd64 CGO_ENABLED=1 \
            go build -buildmode=c-shared \
            -trimpath \
            -ldflags="-s -w -buildid=" \
            -tags="with_debug" \
            -o "$BUILD_DIR/lib/amd64/lib${PKG}.so" \
            ./cmd/${PKG}

      - name: Build for Linux ARM64
        run: |
          echo "Building for Linux ARM64..."
          cd $WORKING_DIR
          GOOS=linux GOARCH=arm64 CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc \
            go build -buildmode=c-shared \
            -trimpath \
            -ldflags="-s -w -buildid=" \
            -tags="with_debug" \
            -o "$BUILD_DIR/lib/arm64/lib${PKG}.so" \
            ./cmd/${PKG}

      - name: Build for Linux 386
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          echo "Building for Linux 386..."
          GOOS=linux GOARCH=386 CGO_ENABLED=1 CC=i686-linux-gnu-gcc \
            go build -buildmode=c-shared \
            -trimpath \
            -ldflags="-s -w -buildid=" \
            -tags="with_debug" \
            -o "$BUILD_DIR/lib/386/lib${PKG}.so" \
            ./cmd/${PKG}

      - name: Build for Linux ARMv7
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          echo "Building for Linux ARMv7..."
          GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=1 CC=arm-linux-gnueabihf-gcc \
            go build -buildmode=c-shared \
            -trimpath \
            -ldflags="-s -w -buildid=" \
            -tags="with_debug" \
            -o "$BUILD_DIR/lib/armv7/lib${PKG}.so" \
            ./cmd/${PKG}

      - name: Verify the libraries
        run: |
          echo "Verifying AMD64 library:"
          if [ -f "$BUILD_DIR/lib/amd64/lib${PKG}.so" ]; then
            echo "AMD64 library exists"
            ls -la $BUILD_DIR/lib/amd64/lib${PKG}.so
            file $BUILD_DIR/lib/amd64/lib${PKG}.so
          else
            echo "ERROR: AMD64 library not found"
            exit 1
          fi
          
          echo "Verifying ARM64 library:"
          if [ -f "$BUILD_DIR/lib/arm64/lib${PKG}.so" ]; then
            echo "ARM64 library exists"
            ls -la $BUILD_DIR/lib/arm64/lib${PKG}.so
            file $BUILD_DIR/lib/arm64/lib${PKG}.so
          else
            echo "ERROR: ARM64 library not found"
            exit 1
          fi
          
          echo "Verifying 386 library:"
          if [ -f "$BUILD_DIR/lib/386/lib${PKG}.so" ]; then
            echo "386 library exists"
            ls -la $BUILD_DIR/lib/386/lib${PKG}.so
            file $BUILD_DIR/lib/386/lib${PKG}.so
          else
            echo "ERROR: 386 library not found"
            exit 1
          fi
          
          echo "Verifying ARMv7 library:"
          if [ -f "$BUILD_DIR/lib/armv7/lib${PKG}.so" ]; then
            echo "ARMv7 library exists"
            ls -la $BUILD_DIR/lib/armv7/lib${PKG}.so
            file $BUILD_DIR/lib/armv7/lib${PKG}.so
          else
            echo "ERROR: ARMv7 library not found"
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          git stash -u
          git pull --rebase
          git stash pop || true
          git add $BUILD_DIR/lib
          
          if git diff --staged --quiet; then
            echo "No changes detected in Linux libraries. Skipping commit."
          else
            echo "Changes detected in Linux libraries. Creating commit..."
            git commit -m "Build Linux libraries ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            git push
            echo "Successfully pushed changes to repository."
          fi