name: ios

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BUILD_DIR: native/ios
  SOURCE_DIR: external

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build-ios.yml"
  workflow_dispatch:
  workflow_run:
    workflows: ["listen", "ci"]
    types:
      - completed

jobs:
  parse-info:
    uses: ./.github/workflows/parse-info.yml
    with:
      path: 'pubspec.yaml'
      target: 'ios'

  build-ios:
    runs-on: macos-latest
    needs: parse-info
    env:
      PKG: ${{ needs.parse-info.outputs.name_lower }}
      PKG_TITLE: ${{ needs.parse-info.outputs.name_full }}
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Install Xcode Command Line Tools
        run: |
          xcode-select --print-path
          sudo xcode-select --switch /Applications/Xcode.app

      - name: Set up environment variables
        run: |
          echo "BUILD_DIR=$GITHUB_WORKSPACE/$BUILD_DIR" >> $GITHUB_ENV
          if [ -d "$SOURCE_DIR" ]; then
            echo "WORKING_DIR=$GITHUB_WORKSPACE/$SOURCE_DIR" >> $GITHUB_ENV
          else
            echo "WORKING_DIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          fi

      - name: Clean and Create output directories
        run: |
          rm -rf $BUILD_DIR
          mkdir -p $BUILD_DIR/libs/arm64
          mkdir -p $BUILD_DIR/libs/x86_64
          mkdir -p $BUILD_DIR/libs/universal

      - name: Build for iOS arm64 (device)
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          echo "Building for iOS arm64..."
          CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 \
            CC=$(xcrun --sdk iphoneos --find clang) \
            CXX=$(xcrun --sdk iphoneos --find clang++) \
            CGO_CFLAGS="-isysroot $(xcrun --sdk iphoneos --show-sdk-path) -mios-version-min=13.0 -arch arm64" \
            CGO_LDFLAGS="-isysroot $(xcrun --sdk iphoneos --show-sdk-path) -mios-version-min=13.0 -arch arm64" \
            go build -buildmode=c-archive \
            -trimpath \
            -ldflags="-s -w -buildid=" \
            -tags="with_debug ios" \
            -o "$BUILD_DIR/libs/arm64/lib${PKG}.a" \
            ./cmd/${PKG}

      - name: Build for iOS x86_64 (simulator)
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          echo "Building for iOS simulator (x86_64)..."
          CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 \
            CC=$(xcrun --sdk iphonesimulator --find clang) \
            CXX=$(xcrun --sdk iphonesimulator --find clang++) \
            CGO_CFLAGS="-isysroot $(xcrun --sdk iphonesimulator --show-sdk-path) -mios-simulator-version-min=13.0 -arch x86_64" \
            CGO_LDFLAGS="-isysroot $(xcrun --sdk iphonesimulator --show-sdk-path) -mios-simulator-version-min=13.0 -arch x86_64" \
            go build -buildmode=c-archive \
            -trimpath \
            -ldflags="-s -w -buildid=" \
            -tags="with_debug ios" \
            -o "$BUILD_DIR/libs/x86_64/lib${PKG}.a" \
            ./cmd/${PKG}

      - name: Create Universal Binary
        run: |
          echo "Creating universal binary..."
          lipo -create \
            $BUILD_DIR/libs/arm64/lib${PKG}.a \
            $BUILD_DIR/libs/x86_64/lib${PKG}.a \
            -output $BUILD_DIR/libs/universal/lib${PKG}.a

          cp $BUILD_DIR/libs/arm64/lib${PKG}.h $BUILD_DIR/libs/universal/
          
      - name: Create XCFramework
        run: |
          echo "Creating XCFramework..."

          mkdir -p $BUILD_DIR/${PKG_TITLE}Framework-ios-arm64.framework/Headers
          mkdir -p $BUILD_DIR/${PKG_TITLE}Framework-ios-x86_64-simulator.framework/Headers

          cp $BUILD_DIR/libs/arm64/lib${PKG}.h $BUILD_DIR/${PKG_TITLE}Framework-ios-arm64.framework/Headers/
          cp $BUILD_DIR/libs/arm64/lib${PKG}.a $BUILD_DIR/${PKG_TITLE}Framework-ios-arm64.framework/${PKG_TITLE}Framework-ios-arm64
          chmod +x $BUILD_DIR/${PKG_TITLE}Framework-ios-arm64.framework/${PKG_TITLE}Framework-ios-arm64

          cp $BUILD_DIR/libs/x86_64/lib${PKG}.h $BUILD_DIR/${PKG_TITLE}Framework-ios-x86_64-simulator.framework/Headers/
          cp $BUILD_DIR/libs/x86_64/lib${PKG}.a $BUILD_DIR/${PKG_TITLE}Framework-ios-x86_64-simulator.framework/${PKG_TITLE}Framework-ios-x86_64-simulator
          chmod +x $BUILD_DIR/${PKG_TITLE}Framework-ios-x86_64-simulator.framework/${PKG_TITLE}Framework-ios-x86_64-simulator
          
          cat > $BUILD_DIR/${PKG_TITLE}Framework-ios-arm64.framework/Info.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleExecutable</key>
              <string>${PKG_TITLE}Framework-ios-arm64</string>
              <key>CFBundleIdentifier</key>
              <string>com.mon-ius.${PKG_TITLE}Framework</string>
              <key>CFBundleName</key>
              <string>${PKG_TITLE}Framework</string>
              <key>CFBundlePackageType</key>
              <string>FMWK</string>
              <key>CFBundleVersion</key>
              <string>1.0</string>
              <key>MinimumOSVersion</key>
              <string>13.0</string>
          </dict>
          </plist>
          EOF
          
          cat > $BUILD_DIR/${PKG_TITLE}Framework-ios-x86_64-simulator.framework/Info.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleExecutable</key>
              <string>${PKG_TITLE}Framework-ios-x86_64-simulator</string>
              <key>CFBundleIdentifier</key>
              <string>com.mon-ius.${PKG_TITLE}Framework</string>
              <key>CFBundleName</key>
              <string>${PKG_TITLE}Framework</string>
              <key>CFBundlePackageType</key>
              <string>FMWK</string>
              <key>CFBundleVersion</key>
              <string>1.0</string>
              <key>MinimumOSVersion</key>
              <string>13.0</string>
          </dict>
          </plist>
          EOF

          ls -la $BUILD_DIR/${PKG_TITLE}Framework-ios-arm64.framework/
          ls -la $BUILD_DIR/${PKG_TITLE}Framework-ios-x86_64-simulator.framework/
          
          xcodebuild -create-xcframework \
            -framework $BUILD_DIR/${PKG_TITLE}Framework-ios-arm64.framework \
            -framework $BUILD_DIR/${PKG_TITLE}Framework-ios-x86_64-simulator.framework \
            -output $BUILD_DIR/lib${PKG}.xcframework

      - name: Create podspec file
        run: |
          echo "Creating podspec file..."
          GIT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.1.0")
          VERSION=${GIT_TAG#v}
          
          cat > $BUILD_DIR/${PKG}.podspec << EOF
          Pod::Spec.new do |s|
            s.name             = '${PKG_TITLE}Framework'
            s.version          = '${VERSION}'
            s.summary          = '${PKG_TITLE} framework for iOS'
            s.description      = 'A cross-platform library compiled for iOS from Go code.'
            s.homepage         = 'https://github.com/${GITHUB_REPOSITORY}'
            s.license          = { :type => 'GNU General Public License v3.0', :file => 'LICENSE' }
            s.author           = { 'M0nius' => 'm0niusplus@gmail.com' }
            s.source           = { :git => 'https://github.com/${GITHUB_REPOSITORY}.git', :tag => s.version.to_s }
            
            s.ios.deployment_target = '13.0'
            s.swift_version = '5.0'
            
            s.vendored_frameworks = 'platforms/ios/lib${PKG}.xcframework'
            
            s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
            s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
            s.requires_arc = true
          end
          EOF
          
          echo "Created podspec file for version ${VERSION}"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          git stash -u
          git pull --rebase
          git stash pop || true
          git add $BUILD_DIR/libs $BUILD_DIR/lib${PKG}.xcframework $BUILD_DIR/${PKG}.podspec
          
          if git diff --staged --quiet; then
            echo "No changes detected in iOS libraries. Skipping commit."
          else
            echo "Changes detected in iOS libraries. Creating commit..."
            git commit -m "Build iOS libraries ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            git push
            echo "Successfully pushed changes to repository."
          fi